name: Generate Contributor City

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정에 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 기여도 도시 이미지를 생성하는 액션
      - name: Generate City
        uses: b-borza/contributor-city@v1
        with:
          # 토큰은 자동으로 제공되는 것을 사용합니다
          token: ${{ secrets.GITHUB_TOKEN }}
          # 본인 유저네임을 자동으로 가져옵니다
          user: ${{ github.repository_owner }}
          # 생성될 이미지 파일 이름
          output: contributor-city.svg
          # 도시 이름 설정 (원하는 대로 변경 가능)
          city_name: sangwon02-City
          # 도시 테마 설정 (예: dark, light, classic, halloween 등)
          theme: classic

      # 생성된 이미지를 city_output 브랜치에 푸시
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: city_output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}